# Generated by Django 2.0.3 on 2018-04-17 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsone', models.IntegerField(blank=True, null=True)),
                ('pointstwo', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('playerone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matsione', to=settings.AUTH_USER_MODEL)),
                ('playertwo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matsitwo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_round_1_player_1', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('result_round_1_player_2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('result_round_2_player_1', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('result_round_2_player_2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('result_round_3_player_1', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('result_round_3_player_2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lostmatch', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wonmatch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matsi',
            name='result_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match1', to='matsit.Result'),
        ),
        migrations.AddField(
            model_name='matsi',
            name='result_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match2', to='matsit.Result'),
        ),
    ]
